### ISSUE TITLE
Remove container after exit code != 0

### ISSUE THREAD

**Issue by fjukstad** [fjukstad/walrus#14]
When a pipeline stage fails with exit code != 0 walrus should remove the container before reattempting to run the pipeline stage. As of now the user will have to remove the container himself. 

Note to self:
```
$ walrus -version-control=false -i broad-wes-example.json -o broad 
input completed successfully.
bam2fastq failed with exit code 1

?[Thu Sep 21 08:05:08 UTC 2017] picard.sam.SamToFastq INPUT=/walrus/input/NA12878.ga2.exome.maq.raw.bam FASTQ=/walrus/bam2fastq/NA12878.fastq    OUTPUT_PER_RG=false RG_TAG=PU RE_REVERSE=true INTERLEAVE=false INCLUDE_NON_PF_READS=false CLIPPING_MIN_LENGTH=0 READ1_TRIM=0 READ2_TRIM=0 INCLUDE_NON_PRIMARY_ALIGNMENTS=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
?[Thu Sep 21 08:05:08 UTC 2017] Executing as worker@5b5e74215bc4 on Linux 3.16.0-77-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_111-8u111-b14-2ubuntu0.16.10.2-b14; Picard version: 2.6.0-SNAPSHOT
W[Thu Sep 21 08:05:08 UTC 2017] picard.sam.SamToFastq done. Elapsed time: 0.00 minutes.
!Runtime.totalMemory()=2058354688
OTo get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
rException in thread "main" picard.PicardException: Input contains paired reads but no SECOND_END_FASTQ specified.
6	at picard.sam.SamToFastq.doWork(SamToFastq.java:198)
P	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
M	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
F	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)

bjorn@pepi:~/src/walrus-wgs-example$ docker rm bam2fastq
bam2fastq
bjorn@pepi:~/src/walrus-wgs-example$ walrus -version-control=false -i broad-wes-example.json -o broad 
reference completed successfully.
Error: No such container: bam2fastq
Warning: Could not find cached container bam2fastq will re-run the stage
input completed successfully.
...
```

**Comment by fjukstad** [comment]
Solved in 56817b34cacabf0da9312167bc2b7aa20d14da46.
